# Generated by Django 6.0.6 on 2026-07-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_linkedin_profile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_connections_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_post_impressions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_profile_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_search_appearances',
            field=models.IntegerField(default=0),
        ),
    ]
