# Generated by Django 6.0.6 on 2026-07-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_linkedin_connections_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_profile_banner',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_profile_picture',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
