# Generated by Django 6.0.6 on 2026-07-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_linkedin_profile_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_profile_headline',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
