# Generated by Django 6.0.6 on 2026-07-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_facebook_engagement_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facebook_verified_meta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram_verified_meta',
            field=models.BooleanField(default=False),
        ),
    ]
