# Generated by Django 6.0.6 on 2026-07-25 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_twitter_display_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudienceInsightProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('age_demographics_json', models.TextField(blank=True, null=True)),
                ('gender_split_json', models.TextField(blank=True, null=True)),
                ('top_regions_json', models.TextField(blank=True, null=True)),
                ('device_analytics_json', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audience_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorshipDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(default='Sponsorships', max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('payout', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(default='In Negotiation', max_length=50)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('deliverables', models.TextField(blank=True, null=True)),
                ('invoice_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
