# Generated by Django 6.0.6 on 2026-08-01 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_audienceinsightprofile_sponsorshipdeal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(max_length=255)),
                ('total_budget', models.DecimalField(decimal_places=2, default=500000.0, max_digits=12)),
                ('target_reach', models.IntegerField(default=1000000)),
                ('achieved_reach', models.IntegerField(default=850000)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyCreatorRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_name', models.CharField(max_length=255)),
                ('handle', models.CharField(max_length=255)),
                ('category', models.CharField(default='Tech & Gaming', max_length=100)),
                ('primary_platform', models.CharField(default='YouTube', max_length=100)),
                ('followers_count', models.IntegerField(default=500000)),
                ('engagement_rate', models.FloatField(default=4.5)),
                ('monthly_revenue', models.DecimalField(decimal_places=2, default=150000.0, max_digits=12)),
                ('commission_split', models.FloatField(default=15.0)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_creators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyCampaignCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable', models.CharField(default='1 Dedicated YouTube Video + 2 IG Reels', max_length=255)),
                ('payout', models.DecimalField(decimal_places=2, default=75000.0, max_digits=12)),
                ('deliverable_status', models.CharField(default='In Progress', max_length=50)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participating_creators', to='accounts.agencycampaign')),
                ('creator_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_assignments', to='accounts.agencycreatorrelation')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(default='Apex Creator Management', max_length=255)),
                ('logo_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('commission_rate', models.FloatField(default=15.0)),
                ('contact_email', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(default='₹', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agency_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
