# Generated by Django 6.0.6 on 2026-08-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_agencycampaign_agencycreatorrelation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencycreatorrelation',
            name='assigned_manager',
            field=models.CharField(default='Priya Sharma', max_length=255),
        ),
        migrations.AddField(
            model_name='agencycreatorrelation',
            name='sponsorship_rate',
            field=models.DecimalField(decimal_places=2, default=150000.0, max_digits=12),
        ),
    ]
