-- ==========================================
-- Module 7 : Notifications & Reports
-- Sample Data
-- ==========================================

-- Notifications

INSERT INTO notifications
(user_id, creator_id, title, message, type, is_read, link_url)

VALUES

('crt11',
 'crt11',
 'Performance Milestone',
 'Congratulations! Your YouTube channel reached 100K subscribers.',
 'performance_milestone',
 FALSE,
 '/dashboard/analytics'),

('crt11',
 'crt11',
 'Revenue Update',
 'Your July revenue has been updated successfully.',
 'revenue_update',
 TRUE,
 '/dashboard/revenue'),

('crt32',
 'crt32',
 'Monthly Report Generated',
 'Your July performance report is ready for download.',
 'report_generated',
 FALSE,
 '/reports/july2026'),

('crt32',
 'crt32',
 'System Alert',
 'Instagram API synchronization failed. Please reconnect your account.',
 'system_alert',
 FALSE,
 '/settings/social-accounts');


-- ==========================================

-- Generated Reports

INSERT INTO generated_reports
(creator_id,
 report_name,
 report_type,
 period_label,
 start_date,
 end_date,
 pdf_path,
 excel_path,
 status)

VALUES

('crt11',
 'July Revenue Report',
 'monthly',
 'July 2026',
 '2026-07-01',
 '2026-07-31',
 '/reports/july2026.pdf',
 '/reports/july2026.xlsx',
 'generated'),

('crt11',
 'Quarterly Analytics Report',
 'quarterly',
 'Q2 2026',
 '2026-04-01',
 '2026-06-30',
 '/reports/q2_2026.pdf',
 '/reports/q2_2026.xlsx',
 'generated'),

('crt32',
 'Weekly Creator Report',
 'weekly',
 'Week 30',
 '2026-07-20',
 '2026-07-26',
 '/reports/week30.pdf',
 '/reports/week30.xlsx',
 'processing');

 -- ==========================================
-- Module 7 : Test Queries
-- ==========================================

-- View all notifications

SELECT * FROM notifications;


-- View all generated reports

SELECT * FROM generated_reports;


-- Unread notifications

SELECT *
FROM notifications
WHERE is_read = FALSE;


-- Notifications of a particular user

SELECT *
FROM notifications
WHERE user_id = 'crt11'
ORDER BY created_at DESC;


-- Revenue related notifications

SELECT *
FROM notifications
WHERE type = 'revenue_update';


-- Reports generated by a creator

SELECT *
FROM generated_reports
WHERE creator_id = 'crt11';


-- Monthly reports

SELECT *
FROM generated_reports
WHERE report_type = 'monthly';


-- Successfully generated reports

SELECT *
FROM generated_reports
WHERE status = 'generated';


-- Reports currently processing

SELECT *
FROM generated_reports
WHERE status = 'processing';


-- Reports ordered by latest

SELECT *
FROM generated_reports
ORDER BY created_at DESC;